name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Coq 8.19 + MathComp 2.1 via opam
      - name: Setup Coq
        uses: coq-community/setup-coq@v2
        with:
          coq-version: "8.19"
          ocaml-compiler: "4.14"
          install: "coq-mathcomp-ssreflect.2.1.0"

      - name: Compile project
        run: make -k all


