name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Coq 8.19 + MathComp 2.1
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y coq-ssreflect libssreflect-ocaml-dev \
                                   libcoq-mathcomp-ssreflect-dev

      - name: Compile project
        run: make -k all


