name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.1
          dune-cache: true
      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: |
          opam install -y \
            coq.8.18.0 \
            coq-mathcomp-ssreflect.2.4.0 \
            coq-mathcomp-algebra.2.4.0 \
            coq-mathcomp-fingroup.2.4.0
      - run: opam exec -- dune build @all
