name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 – Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 – Coq 8.18 + MathComp installieren (über offizielles PPA)
      - name: Install Coq 8.18 + MathComp (Ubuntu)
        run: |
          sudo apt-get update -qq
          # Pakete, die add-apt-repository ermöglichen
          sudo apt-get install -y --no-install-recommends \
               software-properties-common gnupg lsb-release
          # offizielles Coq-PPA hinzufügen
          sudo add-apt-repository -y ppa:coq/stable
          sudo apt-get update -qq
          # Coq + MathComp + Finmap installieren
          sudo apt-get install -y \
               coq \
               coq-ssreflect \
               coq-mathcomp-algebra \
               coq-mathcomp-fingroup \
               coq-mathcomp-finmap

      # 3 – Projekt kompilieren
      - name: Compile project
        run: make -k all


