name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: coqorg/coq:8.18.0
      options: --user root          # root erlaubt einfaches Schreiben

    env:
      OPAMYES: "true"               # nie interaktiv nachfragen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init opam & install MathComp
        run: |
          # opam einrichten (nichts interaktiv, keine Sandbox)
          opam init -a --disable-sandboxing --bare
          eval $(opam env)

          # MathComp-Pakete installieren (Versionen passend zu Coq 8.18)
          opam install \
            mathcomp-ssreflect.1.17.0 \
            mathcomp-fingroup.1.17.0 \
            coq-finmap.1.5.2

      - name: Compile project
        run: make -k all

