name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Coq-Image als Root starten (schreibt problemlos ins Arbeitsverz.)
    container:
      image: coqorg/coq:8.18.0
      options: --user root

    steps:
      # 1 Quellcode auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 MathComp (1.17) + Finmap (1.5) via opam installieren
      - name: Install MathComp via opam
        run: |
          # opam ist bereits initialisiert (switch = coq.8.18.0)
          opam update -q
          opam install -y \
            mathcomp-ssreflect.1.17.0 \
            mathcomp-fingroup.1.17.0 \
            coq-finmap.1.5.2
          eval $(opam env)   # Pfade in diese Shell exportieren

      # 3 Projekt kompilieren
      - name: Compile project
        run: make -k all

