name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest          # GitHub-Runner
    container:
      image: coqorg/coq:8.18.0      # offizielles, vorhandenes Coq-Image

    steps:
      # 1 – Repository auschecken
      - name: Checkout
        uses: actions/checkout@v4

      # 2 – MathComp (1.17) & Finmap nachinstallieren
      - name: Install MathComp
        run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            coq-mathcomp-ssreflect \
            coq-mathcomp-fingroup \
            coq-mathcomp-finmap

      # 3 – Projekt kompilieren
      - name: Compile project
        run: make -k all
