name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Coq 8.18 + MathComp 1.17
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y coq libcoq-ssreflect libcoq-mathcomp-ssreflect
      - name: Compile project
        run: make -k all
