name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: coqorg/coq:8.18.0
      options: --user root            # vermeidet Rechte-Probleme im Container

    env:
      OPAMYES: "true"                 # opam nie interaktiv fragen

    steps:
      # 1 — Quelltext holen
      - name: Checkout
        uses: actions/checkout@v4

      # 2 — opam initialisieren, *einfachen* Switch anlegen, Pakete holen
      - name: Init opam & install deps
        run: |
          # (a) opam Grundkonfig (ohne Sandbox)
          opam init --bare --disable-sandboxing -a
          eval $(opam env)

          # (b) *Einfachen* Switch »coq818« mit OCaml 4.14 anlegen
          opam switch create coq818 ocaml-base-compiler.4.14.1
          eval $(opam env --switch=coq818)

          # (c) offizielles Coq-Repository hinzufügen
          opam repository add coq-released https://coq.inria.fr/opam/released

          # (d) Coq + MathComp + Finmap installieren
          opam install -y \
               coq.8.18.0 \
               mathcomp-ssreflect.1.17.0 \
               mathcomp-fingroup.1.17.0 \
               coq-finmap.1.5.2

      # 3 — Projekt bauen
      - name: Compile project
        run: make -k all
