name: Coq CI

on:
  push:
    branches: [ "**" ]        # alle Branches
  pull_request:               # auch PR-Builds

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPAMYES: "true"         # opam nie interaktiv fragen

    steps:
    # ------------------------------------------------------------
    # 1. Repository auschecken
    # ------------------------------------------------------------
    - name: Checkout sources
      uses: actions/checkout@v4

    # ------------------------------------------------------------
    # 2. OCaml / opam einrichten (offizieller Action)
    #    + Coq-Repos registrieren
    # ------------------------------------------------------------
    - name: Set up OCaml 4.14 + opam
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.1
        opam-repositories: |
          default:      https://opam.ocaml.org
          coq-released: https://coq.inria.fr/opam/released
          coq-extra-dev: https://coq.inria.fr/opam/extra-dev  # ← Finmap liegt hier

    # ------------------------------------------------------------
    # 3. Coq-Toolchain & MathComp installieren
    # ------------------------------------------------------------
    - name: Install Coq toolchain
      run: |
        opam update
        opam install -y \
             coq.8.18.0 \
             coq-mathcomp-ssreflect.1.17.0 \
             coq-mathcomp-fingroup.1.17.0 \
             coq-finmap.1.5.2

    # ------------------------------------------------------------
    # 4. (optional) opam-Cache für schnellere Folgeläufe
    # ------------------------------------------------------------
    - name: Cache opam root
      uses: actions/cache@v3
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    # ------------------------------------------------------------
    # 5. Projekt bauen
    # ------------------------------------------------------------
    - name: Build with make
      run: |
        eval $(opam env)   # Shell in den neuen Switch einhängen
        make -k all
