# .github/workflows/ci.yml
name: Coq build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: coqorg/coq:8.18      #  <── fixed tag
      options: --user root        # stay root inside container

    steps:
      - uses: actions/checkout@v4

      - name: Install MathComp packages
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam update
          opam install -y \
            coq-mathcomp-ssreflect \
            coq-mathcomp-fingroup \
            coq-mathcomp-finmap

      - name: Build project
        run: make -k all           # adapt if you use dune, etc.
