name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Container mit Root-User starten
    container:
      image: coqorg/coq:8.18.0
      options: --user root

    steps:
      # 1 – Repository auschecken (läuft jetzt mit Root-Rechten)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 – MathComp + Finmap installieren
      - name: Install MathComp
        run: |
          apt-get update -qq
          apt-get install -y \
            coq-mathcomp-ssreflect \
            coq-mathcomp-fingroup \
            coq-mathcomp-finmap

      # 3 – Projekt kompilieren
      - name: Compile project
        run: make -k all

