name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest        # GitHub-Runner
    container:
      image: mathcomp/mathcomp:1.17-coq8.18   # enthält Coq + MathComp + Finmap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile project
        run: make -k all



