name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Offizielles Coq-Docker-Image (enthält opam)
    container:
      image: coqorg/coq:8.18.0
      options: --user root          # vermeidet Rechte­probleme im Container

    env:
      OPAMYES:   "true"             # opam niemals interaktiv fragen
      OPAMCOLOR: "always"

    steps:
      # ------------------------------------------------------------
      # 1. Repository auschecken
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------------
      # 2. opam initialisieren, Switch anlegen, Abhängigkeiten holen
      # ------------------------------------------------------------
      - name: Init opam & install dependencies
        run: |
          # Grundsetup ohne Sandbox
          opam init --bare --disable-sandboxing -a
          eval $(opam env)

          # Neuer Switch „coq818“
          opam switch create coq818 ocaml-base-compiler.4.14.1
          eval $(opam env --switch=coq818)

          # Coq-Repository hinzufügen + Index laden
          opam repository add coq-released https://coq.inria.fr/opam/released
          opam update

          # Coq und MathComp-Pakete installieren
          opam install -y \
               coq.8.18.0 \
               coq-mathcomp-ssreflect.1.17.0 \
               coq-mathcomp-fingroup.1.17.0 \
               coq-finmap.1.5.2

      # ------------------------------------------------------------
      # 3. Projekt kompilieren
      # ------------------------------------------------------------
      - name: Build with make
        run: make -k all
