name: Coq build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Coq 8.18 + MathComp (Ubuntu)
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:coq/released
        sudo apt-get update -qq
        sudo apt-get install -y coq \
                                coq-mathcomp-ssreflect \
                                coq-mathcomp-fingroup \
                                coq-mathcomp-finmap
